version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    
    environment:
      # Credenciales
      POSTGRES_PASSWORD: postgres123
      POSTGRES_USER: postgres
      POSTGRES_DB: stp-sgc-local

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./DDL.sql:/docker-entrypoint-initdb.d/DDL.sql

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    
    environment:
      PGADMIN_DEFAULT_EMAIL: noel.bejarano@stpmex.com
      PGADMIN_DEFAULT_PASSWORD: pgadminLocal!
    
    ports:
      - "5050:80"
    
    depends_on:
      - db
      
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      
volumes:
  postgres_data:
  pgadmin_data: